### ISSUE TITLE
allow skipping of flag parse errors

### ISSUE THREAD

**Issue by rsteube** [rsteube/carapace#611]

**Comment by rsteube** [comment]
fyi @iandol

**Comment by maxlandon** [comment]
Very interested in this:
I have a library which allows people to add validations to their flags (or limit the possible choices).
See [here](https://github.com/reeflective/flags/wiki/Validations) for an example and explanations if some are needed.

The problem arising, for instance with map values (ex: `-flag map:value`) is that as soon as `-flag |` is entered, carapace will return an error and will not propose any completions regardless. 

Suppress does not work either, since the error is returned from here, in `complete.go`:
https://github.com/rsteube/carapace/blob/987ec888591636ef36af413c67e26dbffb6b3623/complete.go#L30

Thanks a lot !

**Comment by iandol** [comment]
I continue to hit many situations where completion just fails when I need a path, I am forced to run `zsh` from elvish so I can complete a command then go back to elvish, but this is really disruptive...

**Comment by rsteube** [comment]
@iandol would be good to know where this happens though. I am only using a small portion of the completers so I might not be aware when sth. is amiss.

**Comment by iandol** [comment]
Hi @rsteube, sure I will do. One problem was actually user error in that I made a custom completer and I don't know why but the `positionalany` was not working:

```yaml
name: scrivomatic
description: wrapper for pandocomatic + pandoc
flags:
    -i, --input=: Input file
    -o, --output=: Output file. Optional for pandocomatic.
    -y, --yaml=: Specify which YAML file for pandocomatic.
    -t, --to=: Pandoc Format. Optional for pandocomatic.
    -c, --command=: Tool to use = pandocomatic | panzer
    -p, --path=: Additional Path to Search for Commands.
    -z, --data-dir=: Pandoc data dir.
    -b, --build: For LaTeX output, run latexmk
    -B, --buildclean: For LaTeX output, run latexmk and cleanup
    -d, --dry-run: Dry run.
    -v, --verbose, --no-verbose: Verbose output.
    -l, --log, --no-log: View log in Console.app.
    -h, --help: display this help and exit
completion:
    flag:
        input: ["$files"]
        output: ["$files"]
        yaml: ["$files([.yaml])"]
        to: ["$(pandoc --list-output-formats)"]
        command:
            - "pandocomatic\trun pandocomatic\tcyan"
            - "panzer\trun panzer (deprecated and untested)\tcyan"
        path: ["$directories"]
        data-dir: ["$directories"]
    positionalany: ["$files"]
```

```
error: no candidates

me » ~ 
▶︎ scrivomatic -l -v -- te[tab]
```

I had two problems, first it appears my syntax was not valid: `-l, --log, --no-log: View log in Console.app.` - I need to remove the `--no-log` flag etc. The second problem was that the order is important, I had `positionalany` after `flag`, if I put it first:

```yaml
completion:
    positionalany: ["$files"]
    flag:
        input: ["$files"]
        output: ["$files"]
        yaml: ["$files([.yaml])"]
        to: ["$(pandoc --list-output-formats)"]
        command:
            - "pandocomatic\trun pandocomatic\tcyan"
            - "panzer\trun panzer (deprecated and untested)\tcyan"
        path: ["$directories"]
        data-dir: ["$directories"]
```

With these two fixes now the [tab] completes the file. Perhaps this is expected and it is my fault?
